package com.skittle.backrooms.objects.blocks.dimensional;

public enum DoorType
{
	WHITE_WOODEN_DOOR,
	BEIGE_WOODEN_DOOR,
	DARK_WOODEN_DOOR,
	GRAY_METAL_DOOR,
	GRAY_METAL_MAINTENANCE_DOOR,
	BLACK_METAL_DOOR,
	MAINTENANCE_METAL_DOOR,
	RUSTY_METAL_DOOR,
	WHITE_METAL_DOOR_GLOWING
}
