package com.skittle.backrooms.init;

import java.util.ArrayList;
import java.util.List;

import com.skittle.backrooms.objects.blocks.hotelcarpet.HotelCarpetRed;
import com.skittle.backrooms.objects.blocks.hotelcarpet.HotelCarpetGreen;
import com.skittle.backrooms.objects.blocks.AntiqueWallLight;
import com.skittle.backrooms.objects.blocks.BackroomsDoor;
import com.skittle.backrooms.objects.blocks.BackroomsDoorBlock;
import com.skittle.backrooms.objects.blocks.CementBricks;
import com.skittle.backrooms.objects.blocks.CementBricksPillar;
import com.skittle.backrooms.objects.blocks.CheckeredBlock;
import com.skittle.backrooms.objects.blocks.ConcretePillar;
import com.skittle.backrooms.objects.blocks.ElevatorButton;
import com.skittle.backrooms.objects.blocks.FluorescentCeilingLight;
import com.skittle.backrooms.objects.blocks.FluorescentWallLight;
import com.skittle.backrooms.objects.blocks.Glass;
import com.skittle.backrooms.objects.blocks.Concrete;
import com.skittle.backrooms.objects.blocks.Light;
import com.skittle.backrooms.objects.blocks.Metal;
import com.skittle.backrooms.objects.blocks.NoclipBlock;
import com.skittle.backrooms.objects.blocks.Pipe;
import com.skittle.backrooms.objects.blocks.Tile;
import com.skittle.backrooms.objects.blocks.BackroomsStairs;
import com.skittle.backrooms.objects.blocks.Carpet;
import com.skittle.backrooms.objects.blocks.Ceiling;
import com.skittle.backrooms.objects.blocks.Cement;
import com.skittle.backrooms.objects.blocks.TornWallpaper;
import com.skittle.backrooms.objects.blocks.Wallpaper;
import com.skittle.backrooms.objects.blocks.WallpaperPillarTop;
import com.skittle.backrooms.objects.blocks.WoodenBeam;
import com.skittle.backrooms.objects.blocks.WoodenBlock;
import com.skittle.backrooms.objects.blocks.WoodenGlassColumn;
import com.skittle.backrooms.objects.blocks.dimensional.BackroomsDimensionalDoor;
import com.skittle.backrooms.objects.blocks.dimensional.DoorType;
import com.skittle.backrooms.objects.blocks.furniture.FurnitureChair;
import com.skittle.backrooms.objects.blocks.furniture.FurnitureRoundTable;
import com.skittle.backrooms.objects.blocks.furniture.FurnitureSquareTable;

import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;

public class BlockInit
{
	public static final List<Block> BLOCKS = new ArrayList<Block>();

	public static final Block CARPET = new Carpet("carpet", Material.CLOTH);
	public static final Block CARPET_STAIRS = new BackroomsStairs("carpet_stairs", CARPET.getDefaultState(), SoundType.CLOTH, 1.0F, 2.0F);
	public static final Block RED_CARPET = new Carpet("red_carpet", Material.CLOTH);
	public static final Block RED_CARPET_STAIRS = new BackroomsStairs("red_carpet_stairs", RED_CARPET.getDefaultState(), SoundType.CLOTH, 1.0F, 2.0F);
	public static final Block BOTTOM_YELLOW_WALLPAPER = new Wallpaper("bottom_yellow_wallpaper", Material.WOOD);
	public static final Block YELLOW_WALLPAPER = new Wallpaper("yellow_wallpaper", Material.WOOD);
	public static final Block BOTTOM_YELLOW_WALLPAPER_WRONG = new NoclipBlock("bottom_yellow_wallpaper_wrong", Material.WOOD, SoundType.WOOD, 3.0F, 3.0F, "axe");
	public static final Block YELLOW_WALLPAPER_WRONG = new NoclipBlock("yellow_wallpaper_wrong", Material.WOOD, SoundType.WOOD, 3.0F, 3.0F, "axe");
	public static final Block TORN_YELLOW_WALLPAPER_1 = new TornWallpaper("torn_yellow_wallpaper_1", Material.WOOD);
	public static final Block TORN_YELLOW_WALLPAPER_2 = new TornWallpaper("torn_yellow_wallpaper_2", Material.WOOD);
	public static final Block TORN_YELLOW_WALLPAPER_3 = new TornWallpaper("torn_yellow_wallpaper_3", Material.WOOD);
	public static final Block TORN_YELLOW_WALLPAPER_4 = new TornWallpaper("torn_yellow_wallpaper_4", Material.WOOD);
	public static final Block BOTTOM_DOTTED_YELLOW_WALLPAPER = new Wallpaper("bottom_dotted_yellow_wallpaper", Material.WOOD);
	public static final Block DOTTED_YELLOW_WALLPAPER = new Wallpaper("dotted_yellow_wallpaper", Material.WOOD);
	public static final Block BOTTOM_DOTTED_YELLOW_WALLPAPER_WRONG = new NoclipBlock("bottom_dotted_yellow_wallpaper_wrong", Material.WOOD, SoundType.WOOD, 3.0F, 3.0F, "axe");
	public static final Block DOTTED_YELLOW_WALLPAPER_WRONG = new NoclipBlock("dotted_yellow_wallpaper_wrong", Material.WOOD, SoundType.WOOD, 3.0F, 3.0F, "axe");
	public static final Block TORN_DOTTED_YELLOW_WALLPAPER_1 = new TornWallpaper("torn_dotted_yellow_wallpaper_1", Material.WOOD);
	public static final Block TORN_DOTTED_YELLOW_WALLPAPER_2 = new TornWallpaper("torn_dotted_yellow_wallpaper_2", Material.WOOD);
	public static final Block TORN_DOTTED_YELLOW_WALLPAPER_3 = new TornWallpaper("torn_dotted_yellow_wallpaper_3", Material.WOOD);
	public static final Block TORN_DOTTED_YELLOW_WALLPAPER_4 = new TornWallpaper("torn_dotted_yellow_wallpaper_4", Material.WOOD);
	public static final Block WHITE_WALLPAPER = new Wallpaper("white_wallpaper", Material.WOOD);
	public static final Block TORN_WHITE_WALLPAPER_1 = new TornWallpaper("torn_white_wallpaper_1", Material.WOOD);
	public static final Block TORN_WHITE_WALLPAPER_2 = new TornWallpaper("torn_white_wallpaper_2", Material.WOOD);
	public static final Block TORN_WHITE_WALLPAPER_3 = new TornWallpaper("torn_white_wallpaper_3", Material.WOOD);
	public static final Block TORN_WHITE_WALLPAPER_4 = new TornWallpaper("torn_white_wallpaper_4", Material.WOOD);
	public static final Block DOTTED_WHITE_WALLPAPER = new Wallpaper("dotted_white_wallpaper", Material.WOOD);
	public static final Block TORN_DOTTED_WHITE_WALLPAPER_1 = new TornWallpaper("torn_dotted_white_wallpaper_1", Material.WOOD);
	public static final Block TORN_DOTTED_WHITE_WALLPAPER_2 = new TornWallpaper("torn_dotted_white_wallpaper_2", Material.WOOD);
	public static final Block TORN_DOTTED_WHITE_WALLPAPER_3 = new TornWallpaper("torn_dotted_white_wallpaper_3", Material.WOOD);
	public static final Block TORN_DOTTED_WHITE_WALLPAPER_4 = new TornWallpaper("torn_dotted_white_wallpaper_4", Material.WOOD);
	public static final Block TILE = new Tile("tile", Material.ROCK);
	public static final Block LIGHT_ON = new Light("light_on", Material.REDSTONE_LIGHT, SoundType.GLASS, 2.0F, 1.0F, 15, true);
	public static final Block LIGHT_OFF = new Light("light_off", Material.REDSTONE_LIGHT, SoundType.GLASS, 2.0F, 1.0F, 0, true);
	public static final Block CEMENT = new Cement("cement", Material.ROCK);
	public static final Block CEMENT_STAIRS = new BackroomsStairs("cement_stairs", CEMENT.getDefaultState(), SoundType.STONE, 3.0F, 5.0F);
	public static final Block CEMENT_BRICKS = new CementBricks("cement_bricks", Material.ROCK);
	public static final Block GRAY_CONCRETE = new Concrete("gray_concrete", Material.ROCK);
	public static final Block GRAY_CONCRETE_COLUMN = new ConcretePillar("gray_concrete_column", Material.ROCK);
	public static final Block WHITE_CONCRETE = new Concrete("white_concrete", Material.ROCK);
	public static final Block WHITE_CONCRETE_BOTTOM = new CementBricksPillar("white_concrete_bottom", Material.ROCK, true);
	public static final Block PIPE = new Pipe("pipe", Material.IRON);
	public static final Block ORANGE_CEMENT_BRICKS = new CementBricks("orange_cement_bricks", Material.ROCK);
	public static final Block ORANGE_CEMENT_BRICKS_TOP = new CementBricksPillar("orange_cement_bricks_top", Material.ROCK, true);
	public static final Block ORANGE_CEMENT_BRICKS_BOTTOM = new CementBricksPillar("orange_cement_bricks_bottom", Material.ROCK, true);
	public static final Block CEILING = new Ceiling("ceiling", Material.ROCK);
	public static final Block STONE_CHECKERED = new CheckeredBlock("stone_checkered", Material.ROCK);
	public static final Block FLUORESCENT_CEILING_LAMP_ON = new FluorescentCeilingLight("fluorescent_ceiling_lamp_on", Material.REDSTONE_LIGHT, SoundType.STONE, 2.0F, 1.0F, 15);
	public static final Block FLUORESCENT_CEILING_LAMP_DAMAGED = new FluorescentCeilingLight("fluorescent_ceiling_lamp_damaged", Material.REDSTONE_LIGHT, SoundType.STONE, 2.0F, 1.0F, 8);
	public static final Block FLUORESCENT_CEILING_LAMP_OFF = new FluorescentCeilingLight("fluorescent_ceiling_lamp_off", Material.REDSTONE_LIGHT, SoundType.STONE, 2.0F, 1.0F, 0);
	public static final Block FLUORESCENT_WALL_VERTICAL_LAMP = new FluorescentWallLight("fluorescent_wall_vertical_lamp", Material.REDSTONE_LIGHT, SoundType.STONE, 2.0F, 1.0F, 15);
	public static final Block ILLUMINATED_GLASS = new Glass("illuminated_glass", Material.GLASS, true, 15);
	public static final Block TINTED_GLASS = new Glass("tinted_glass", Material.GLASS, true, 0);
	public static final Block RED_WALLPAPER = new Wallpaper("red_wallpaper", Material.WOOD);
	public static final Block RED_WALLPAPER_COLUMN = new Wallpaper("red_wallpaper_column", Material.WOOD);
	public static final Block RED_WALLPAPER_COLUMN_TOP = new WallpaperPillarTop("red_wallpaper_column_top", Material.WOOD);
	
	public static final Block WOODEN_COLUMN_TOP = new WoodenBlock("wooden_column_top", Material.WOOD);
	public static final Block WOODEN_COLUMN_MIDDLE = new WoodenBlock("wooden_column_middle", Material.WOOD);
	public static final Block WOODEN_COLUMN_BOTTOM = new WoodenBlock("wooden_column_bottom", Material.WOOD);
	public static final Block WOODEN_BEAM = new WoodenBeam("wooden_beam", Material.WOOD);
	public static final Block WOODEN_CEILING = new WoodenBlock("wooden_ceiling", Material.WOOD);
	public static final Block WOODEN_GLASS = new WoodenGlassColumn("wooden_glass", Material.WOOD, 0, true);
	public static final Block WOODEN_GLASS_EXTENDED = new WoodenGlassColumn("wooden_glass_extended", Material.WOOD, 15, false);
	public static final Block WHITE_STONE_BRICKS = new CementBricks("white_stone_bricks", Material.ROCK);
	public static final Block GREEN_PATTERNED_HOTEL_CARPET = new HotelCarpetGreen("green_patterned_hotel_carpet", Material.CLOTH);
	public static final Block RED_PATTERNED_HOTEL_CARPET = new HotelCarpetRed("red_patterned_hotel_carpet", Material.CLOTH);
	public static final Block RED_HOTEL_CARPET = new Carpet("red_hotel_carpet", Material.CLOTH);
	public static final Block WOODEN_CHAIR = new FurnitureChair("wooden_chair", Material.WOOD);
	public static final Block WOODEN_SQUARE_TABLE = new FurnitureSquareTable("wooden_square_table", Material.WOOD);
	public static final Block WOODEN_ROUND_TABLE = new FurnitureRoundTable("wooden_round_table", Material.WOOD);
	public static final Block ANTIQUE_DOUBLE_SCONCE = new AntiqueWallLight("antique_double_sconce", Material.REDSTONE_LIGHT, SoundType.WOOD, 2.0F, 1.0F, 15);
	public static final Block WALL_CANDLE = new AntiqueWallLight("wall_candle", Material.REDSTONE_LIGHT, SoundType.WOOD, 2.0F, 1.0F, 15);
	public static final Block ANTIQUE_ELEVATOR_BUTTONS = new ElevatorButton("antique_elevator_button", Material.WOOD, SoundType.WOOD, 2.0F, 2.0F, "axe", 1005, 1003, 0.5F, 62.0F, 0.5F, true);
	public static final Block MODERN_ELEVATOR_BUTTONS = new ElevatorButton("modern_elevator_button", Material.IRON, SoundType.STONE, 2.0F, 2.0F, "pickaxe", 1003, 1004, 0.5F, 62.0F, 0.5F, true);
	public static final Block METAL = new Metal("metal", Material.IRON);
	
	public static final Block WHITE_WOODEN_DOOR = new BackroomsDoor("white_wooden_door", Material.WOOD, SoundType.WOOD, 3.0F, 3.0F, "axe");
	public static final Block METAL_DOOR = new BackroomsDoor("metal_door", Material.ANVIL, SoundType.METAL, 3.0F, 3.0F, "pickaxe");
	public static final Block METAL_MAINTENANCE_DOOR = new BackroomsDoor("metal_maintenance_door", Material.ANVIL, SoundType.METAL, 3.0F, 3.0F, "pickaxe");
	public static final Block METAL_BLACK_DOOR = new BackroomsDoor("metal_black_door", Material.ANVIL, SoundType.METAL, 3.0F, 3.0F, "pickaxe");
	public static final Block OFFICE_WOODEN_DOOR = new BackroomsDoor("office_wooden_door", Material.WOOD, SoundType.WOOD, 3.0F, 3.0F, "axe");
	public static final Block OFFICE_WOODEN_GLASS_DOOR = new BackroomsDoor("office_wooden_glass_door", Material.WOOD, SoundType.WOOD, 3.0F, 3.0F, "axe");
	
	public static final Block WHITE_WOODEN_DOOR_BLOCK_BOTTOM = new BackroomsDimensionalDoor("white_wooden_door_block_bottom", Material.WOOD, SoundType.WOOD, DoorType.WHITE_WOODEN_DOOR, 3.0F, 3.0F, false);
	public static final Block WHITE_WOODEN_DOOR_BLOCK_TOP = new BackroomsDimensionalDoor("white_wooden_door_block_top", Material.WOOD, SoundType.WOOD, DoorType.WHITE_WOODEN_DOOR, 3.0F, 3.0F, false);
	public static final Block METAL_DOOR_BLOCK_BOTTOM = new BackroomsDimensionalDoor("metal_door_block_bottom", Material.ANVIL, SoundType.METAL, DoorType.GRAY_METAL_DOOR, 3.0F, 3.0F, false);
	public static final Block METAL_DOOR_BLOCK_TOP = new BackroomsDimensionalDoor("metal_door_block_top", Material.ANVIL, SoundType.METAL, DoorType.GRAY_METAL_DOOR, 3.0F, 3.0F, false);
	public static final Block METAL_MAINTENANCE_DOOR_BLOCK_BOTTOM = new BackroomsDimensionalDoor("metal_maintenance_door_block_bottom", Material.ANVIL, SoundType.METAL, DoorType.GRAY_METAL_MAINTENANCE_DOOR, 3.0F, 3.0F, false);
	public static final Block METAL_MAINTENANCE_DOOR_BLOCK_TOP = new BackroomsDimensionalDoor("metal_maintenance_door_block_top", Material.ANVIL, SoundType.METAL, DoorType.GRAY_METAL_MAINTENANCE_DOOR, 3.0F, 3.0F, false);
	public static final Block METAL_BLACK_DOOR_BLOCK_BOTTOM = new BackroomsDimensionalDoor("metal_black_door_block_bottom", Material.ANVIL, SoundType.METAL, DoorType.BLACK_METAL_DOOR, 3.0F, 3.0F, false);
	public static final Block METAL_BLACK_DOOR_BLOCK_TOP = new BackroomsDimensionalDoor("metal_black_door_block_top", Material.ANVIL, SoundType.METAL, DoorType.BLACK_METAL_DOOR, 3.0F, 3.0F, false);
	public static final Block RUSTY_METAL_DOOR_BLOCK_BOTTOM = new BackroomsDimensionalDoor("rusty_metal_door_block_bottom", Material.ANVIL, SoundType.METAL, DoorType.RUSTY_METAL_DOOR, 3.0F, 3.0F, false);
	public static final Block RUSTY_METAL_DOOR_BLOCK_TOP = new BackroomsDimensionalDoor("rusty_metal_door_block_top", Material.ANVIL, SoundType.METAL, DoorType.RUSTY_METAL_DOOR, 3.0F, 3.0F, false);
	public static final Block OFFICE_WOODEN_DOOR_BLOCK_BOTTOM = new BackroomsDimensionalDoor("office_wooden_door_block_bottom", Material.WOOD, SoundType.WOOD, DoorType.BEIGE_WOODEN_DOOR, 3.0F, 3.0F, false);
	public static final Block OFFICE_WOODEN_DOOR_BLOCK_TOP = new BackroomsDimensionalDoor("office_wooden_door_block_top", Material.WOOD, SoundType.WOOD, DoorType.BEIGE_WOODEN_DOOR, 3.0F, 3.0F, false);
	public static final Block DARK_WOODEN_DOOR_BLOCK_BOTTOM = new BackroomsDimensionalDoor("dark_wooden_door_block_bottom", Material.WOOD, SoundType.WOOD, DoorType.DARK_WOODEN_DOOR, 3.0F, 3.0F, false);
	public static final Block DARK_WOODEN_DOOR_BLOCK_TOP = new BackroomsDimensionalDoor("dark_wooden_door_block_top", Material.WOOD, SoundType.WOOD, DoorType.DARK_WOODEN_DOOR, 3.0F, 3.0F, false);
	
	public static final Block WHITE_METAL_DOOR_BLOCK_BOTTOM = new BackroomsDimensionalDoor("white_metal_door_block_bottom", Material.WOOD, SoundType.WOOD, DoorType.WHITE_METAL_DOOR_GLOWING, 3.0F, 3.0F, true);
	public static final Block WHITE_METAL_DOOR_BLOCK_TOP = new BackroomsDimensionalDoor("white_metal_door_block_top", Material.WOOD, SoundType.WOOD, DoorType.WHITE_METAL_DOOR_GLOWING, 3.0F, 3.0F, true);
	
}
